  
  services:
    api_gateway:
      build:
        context: ../api_gateway
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
        - FINANCIAL_SERVER_URL=${FINANCIAL_SERVER_URL}
        - NLP_SERVER_URL=${NLP_SERVER_URL}
        - ANALYTICS_SERVER_URL=${ANALYTICS_SERVER_URL}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
      volumes:
        - ../api_gateway/keys:/app/keys:ro
        - ../api_gateway/api_gateway.log:/app/api_gateway.log
      networks:
        - finguard-net

    financial:
      build:
        context: ../financial-server
        dockerfile: Dockerfile
      ports:
        - "8001:8001"
      environment:
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
        - FINANCIAL_SERVER_URL=${FINANCIAL_SERVER_URL}
        - NLP_SERVER_URL=${NLP_SERVER_URL}
        - ANALYTICS_SERVER_URL=${ANALYTICS_SERVER_URL}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
      volumes:
        - ../financial-server/logs/financial_server.log:/app/logs/financial_server.log
      networks:
        - finguard-net

    nlp:
      build:
        context: ../server_4_nlp
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      environment:
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
        - FINANCIAL_SERVER_URL=${FINANCIAL_SERVER_URL}
        - NLP_SERVER_URL=${NLP_SERVER_URL}
        - ANALYTICS_SERVER_URL=${ANALYTICS_SERVER_URL}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
      volumes:
        - ../server_4_nlp/nlp_server.log:/app/nlp_server.log
      networks:
        - finguard-net

    analytics:
      build:
        context: ../server_5_analytics
        dockerfile: Dockerfile
      ports:
        - "8002:8002"
      environment:
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
        - FINANCIAL_SERVER_URL=${FINANCIAL_SERVER_URL}
        - NLP_SERVER_URL=${NLP_SERVER_URL}
        - ANALYTICS_SERVER_URL=${ANALYTICS_SERVER_URL}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
      volumes:
        - ../server_5_analytics/ai_analytics_server.log:/app/ai_analytics_server.log
      networks:
        - finguard-net

  networks:
    finguard-net:
      driver: bridge
