name: Docker Compose CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Compose
        run: |
          docker-compose -f monitoring/docker-compose.yml build
          docker-compose -f monitoring/docker-compose.yml up -d
          docker-compose -f monitoring/docker-compose.yml ps

      - name: Trigger n8n Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.N8N_WEBHOOK_URL }}
          method: POST
          contentType: "application/json"
          body: |
            {
              "trigger": "docker_build_complete",
              "branch": "${{ github.ref_name }}"
            }