name: Docker Compose CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Images
        run: |
          docker compose -f monitoring/docker-compose.yml build
          docker compose -f monitoring/docker-compose.yml push

      - name: Trigger n8n Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.N8N_WEBHOOK_URL }}
          method: POST
          timeout: 30000 

