name: Docker Compose CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file for Docker Compose
        run: |
          cat > monitoring/.env <<EOF
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          FIREBASE_CREDENTIALS_PATH=${{ secrets.FIREBASE_CREDENTIALS_PATH }}
          FINANCIAL_SERVER_URL=${{ secrets.FINANCIAL_SERVER_URL }}
          NLP_SERVER_URL=${{ secrets.NLP_SERVER_URL }}
          ANALYTICS_SERVER_URL=${{ secrets.ANALYTICS_SERVER_URL }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          EOF

      - name: Build & Push Docker Images
        run: |
          docker compose -f monitoring/docker-compose.yml build
          docker compose -f monitoring/docker-compose.yml push

      - name: Trigger n8n Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.N8N_WEBHOOK_URL }}
          method: POST
          timeout: 3000000
